#
#
#
#
#
name: Sync Labels

on:
  push:
    branches:
      - main

  workflow_dispatch:
  schedule:
    - cron:  '00 5 * * *'

jobs:
  sync_labels:
    runs-on: ubuntu-latest

    steps:
    - name: Get OpenATO Workflows
      uses: actions/checkout@v2
      with:
        ref: main
        repository: OpenATO/.github
        path: .github

    - name: Run Label Sync Workflow
      uses: .github/actions/workflows/sync-labels.yml
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

#          token: ${{ secrets.LABEL_TOKEN }}
#           request-token: ${{ secrets.LABEL_TOKEN }}

